#!/bin/bash

sudo /opt/netronome/p4/bin/rtecli tables add -t ingress::espelho_udp_inner -r capture_webcam -m '{ "udp_inner.srcPort" : { "value" : "44299" }, "ipv4_inner.dstAddr" : { "value" : "192.168.58.102" }, "udp_inner.dstPort" : { "value" : "2509" } }' -a '{ "type": "ingress::encaminhaDecapture_inner", "data": { "egressPort": { "value": "v0.2" }, "defaultEgressPort": { "value": "v0.1" }, "dataPort": { "value": "2509" }, "ip_dec1": { "value": "192.168.58.103" }, "port_dec1": { "value": "39705" }, "mac_dec1": { "value": "00:15:4d:00:00:02" } } }'
sudo /opt/netronome/p4/bin/rtecli tables add -t ingress::drop_packet_middleware -r drop_flow_to_webcam -m '{ "ipv4.srcAddr" : { "value" : "192.168.58.102" }, "udp.srcPort" : { "value" : "2509" }, "ipv4.dstAddr" : { "value" : "192.168.58.103" }, "udp.dstPort" : { "value" : "39705" } }' -a '{ "type": "ingress::drop", "data": {} }'

sudo /opt/netronome/p4/bin/rtecli tables add -t ingress::force_egress_port_inner -r forca_porta_v02 -m '{ "ipv4_inner.dstAddr" : { "value" : "192.168.58.102" } }' -a '{ "type": "ingress::change_egress_port", "data": { "egressPort": { "value": "v0.2" } } }'
sudo /opt/netronome/p4/bin/rtecli tables add -t ingress::force_egress_port -r forca_porta_dec_v02 -m '{ "ipv4.dstAddr" : { "value" : "192.168.58.102" } }' -a '{ "type": "ingress::change_egress_port", "data": { "egressPort": { "value": "v0.2" } } }'
