#!/bin/bash

sudo /opt/netronome/p4/bin/rtecli tables -i 0 list-rules
sudo /opt/netronome/p4/bin/rtecli tables -i 1 list-rules
sudo /opt/netronome/p4/bin/rtecli tables -i 2 list-rules
sudo /opt/netronome/p4/bin/rtecli tables -i 3 list-rules
sudo /opt/netronome/p4/bin/rtecli tables -i 4 list-rules
sudo /opt/netronome/p4/bin/rtecli tables -i 5 list-rules
